name: iris_nous_mobile
description: App companion Iris Nous (Android + iPhone) — configura e invia eventi chiamata/musica.
publish_to: "none"
version: 0.4.59+5

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  flutter_secure_storage: ^9.2.2
  mobile_scanner: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
