"""Spanish UI catalog keyed by Italian source strings."""

ES: dict[str, str] = {
    "Menu": "Menú",
    "Tema": "Tema",
    "Chiaro": "Claro",
    "Scuro": "Oscuro",
    "Auto": "Auto",
    "Lingua": "Idioma",
    "Login": "Iniciar sesión",
    "Iscrizione": "Registro",
    "La mia cuffia": "Mi casco",
    "Ecosistema": "Ecosistema",
    "Inizia": "Empezar",
    "Insegna a Iris il tuo pensiero.": "Enséñale a Iris tu pensamiento.",
    "Niente menu infiniti. Tre passi chiari, come quando accendi un dispositivo per la prima volta. Poi musica, casa e chiamate ti seguono — senza toccare.": "Sin menús infinitos. Tres pasos claros, como cuando enciendes un dispositivo por primera vez. Luego la música, la casa y las llamadas te siguen — sin tocar.",
    "Cosa puoi fare": "Lo que puedes hacer",
    "Iniziamo": "Empecemos",
    "Avanti": "Continuar",
    "Indietro": "Atrás",
    "Pensi. Accade.": "Piensas. Sucede.",
    "Ricevi il codice via email": "Recibe el código por correo",
    "Invia il codice via email": "Enviar el código por correo",
    "Come funziona": "Cómo funciona",
    "Chi sei, per Iris.": "Quién eres, para Iris.",
    "Un attimo": "Un momento",
    "Sei pronto.": "Ya estás listo.",
    "Calibrazione": "Calibración",
    "Associa telefono": "Vincular teléfono",
    "I miei dati": "Mis datos",
    "Cambia password": "Cambiar contraseña",
    "Esci": "Salir",
    "Pannello admin": "Panel admin",
    "Mostra password": "Mostrar contraseña",
    "Nascondi password": "Ocultar contraseña",
    "Passa il mouse per vedere la password (su telefono: tocca)": "Pasa el ratón para ver la contraseña (en el teléfono: toca)",
    "Tesi triennale · Informatica · Università degli Studi di Torino": "Tesis de grado · Informática · Universidad de Turín",
    "Università degli Studi di Torino": "Universidad de Turín",
    "Dipartimento di Informatica": "Departamento de Informática",
    "L’interfaccia invisibile": "La interfaz invisible",
    "Pensa. E accade.": "Piensa. Y sucede.",
    "Iris Nous traduce le frequenze della tua mente in azioni fisiche. Accendi la luce, controlla la musica, rispondi alle chiamate. Zero latenza, nessuna voce, nessun movimento. Solo puro intento.": "Iris Nous traduce las frecuencias de tu mente en acciones físicas. Enciende la luz, controla la música, responde a las llamadas. Cero latencia, sin voz, sin movimiento. Solo intención pura.",
    "Entra nella tua area": "Entra en tu espacio",
    "Ingegneria": "Ingeniería",
    "Decodifica neurale": "Decodificación neural",
    "Il pensiero, isolato dal rumore.": "El pensamiento, aislado del ruido.",
    "L’intelligenza artificiale analizza i microvolt del tracciato EEG in tempo reale. Filtra artefatti, isola l’intento e lo rende un comando eseguibile.": "La inteligencia artificial analiza los microvoltios del trazado EEG en tiempo real. Filtra artefactos, aísla la intención y la convierte en un comando ejecutable.",
    "Sintonizzazione personale": "Sintonización personal",
    "Un modello per la tua mente.": "Un modelo para tu mente.",
    "I modelli di machine learning si adattano alla topologia cerebrale unica di chi indossa la cuffia. Pochi secondi di calibrazione: da quel momento Iris ti riconosce.": "Los modelos de machine learning se adaptan a la topología cerebral única de quien lleva el casco. Unos segundos de calibración: desde ese momento Iris te reconoce.",
    "Controllo universale": "Control universal",
    "L’intento diventa automazione.": "La intención se vuelve automatización.",
    "Integrazione fluida con ecosistemi IoT e API di terze parti — Home Assistant, Spotify, il telefono. Nessuna interfaccia da toccare: l’interfaccia definitiva è l’assenza di interfaccia.": "Integración fluida con ecosistemas IoT y API de terceros — Home Assistant, Spotify, el teléfono. Ninguna interfaz que tocar: la interfaz definitiva es la ausencia de interfaz.",
    "Progetto di Tesi di Laurea Triennale": "Proyecto de tesis de grado",
    "Dipartimento di Informatica, Università degli Studi di Torino (UNITO).": "Departamento de Informática, Universidad de Turín (UNITO).",
    "Sede: Torino, Italia.": "Sede: Turín, Italia.",
    "Architettura e Tecnologia": "Arquitectura y tecnología",
    "Acquisizione Segnale": "Adquisición de señal",
    "Pipeline ML": "Pipeline ML",
    "Dispatcher IoT": "Dispatcher IoT",
    "Documentazione API": "Documentación API",
    "Sviluppo e Contatti": "Desarrollo y contactos",
    "Progettazione e Sviluppo:": "Diseño y desarrollo:",
    "GitHub Repository": "Repositorio GitHub",
    "Demo Video": "Vídeo demo",
    "Contatta l’Autore": "Contacta al autor",
    "Copyright © 2026 Iris Nous. Tutti i diritti riservati.": "Copyright © 2026 Iris Nous. Todos los derechos reservados.",
    "Locale": "Local",
    "Online": "En línea",
    "Sei sul sito online: qui vivono gli account del telefono e Spotify. Quelli creati solo sul PC locale non esistono qui.": "Estás en el sitio en línea: aquí viven las cuentas del teléfono y de Spotify. Las creadas solo en el PC local no existen aquí.",
    "Accesso amministratore tesi: username": "Acceso de administrador de tesis: usuario",
    "(password di default admin123, oppure quella impostata su Render).": "(contraseña por defecto admin123, o la configurada en Render).",
    "Password non corretta. Controlla username e password, senza spazi extra.": "Contraseña incorrecta. Comprueba usuario y contraseña, sin espacios de más.",
    "pensa,": "piensa,",
    "agisci,": "actúa,",
    "crea.": "crea.",
    "Come parlare a Siri, ma pensando.": "Como hablarle a Siri, pero pensando.",
    "Chiamate, musica, luci: l’azione parte. Senza aprire lo schermo.": "Llamadas, música, luces: la acción arranca. Sin abrir la pantalla.",
    "Scorri": "Desliza",
    "L’interfaccia dopo lo schermo è la mente.": "La interfaz después de la pantalla es la mente.",
    "Oggi dai un comando a voce. Domani lo pensi: la luce si accende, la canzone cambia, la chiamata si chiude.": "Hoy das un comando de voz. Mañana lo piensas: la luz se enciende, la canción cambia, la llamada se cierra.",
    "Impara te.": "Te aprende.",
    "Poi esegue il pensiero.": "Luego ejecuta el pensamiento.",
    "Come il Face ID riconosce un viso, Iris si sintonizza sul tuo intento. Non un dizionario da studiare, non un menù da confermare: la cuffia impara te, e da quel momento pensare è già agire.": "Como Face ID reconoce un rostro, Iris se sintoniza con tu intención. No es un diccionario que estudiar, ni un menú que confirmar: el casco te aprende, y desde ese momento pensar ya es actuar.",
    "Tu vivi.": "Tú vives.",
    "Lui resta in tasca.": "Él se queda en el bolsillo.",
    "Non un sistema che ti interrompe con domande. Il canale della chiamata si apre solo quando squilla; quello della musica solo mentre ascolti. Pensi, succede, e lo schermo non ti chiede niente.": "No es un sistema que te interrumpe con preguntas. El canal de la llamada se abre solo cuando suena; el de la música solo mientras escuchas. Piensas, sucede, y la pantalla no te pide nada.",
    "Quale luce.": "Qué luz.",
    "Quale stanza.": "Qué habitación.",
    "Un sì, o un no.": "Un sí, o un no.",
    "Hai più dispositivi. Pensi ad accendere: Alexa (o la casa connessa) ti propone quale, tu pensi sì o no, e si chiude. Il futuro della domotica non è un altro telecomando: è l’intento, nel momento giusto.": "Tienes varios dispositivos. Piensas en encender: Alexa (o la casa conectada) te propone cuál, tú piensas sí o no, y se cierra. El futuro de la domótica no es otro mando: es la intención, en el momento justo.",
    "La traccia dopo": "La pista siguiente",
    "è un pensiero.": "es un pensamiento.",
    "Non stai guardando lo schermo: stai ascoltando. Come chiederesti a Siri di saltare il brano — solo che non dici niente, e la musica va avanti lo stesso.": "No estás mirando la pantalla: estás escuchando. Como le pedirías a Siri que saltara el tema — solo que no dices nada, y la música sigue igual.",
    "Un attimo.": "Un momento.",
    "Poi di nuovo silenzio.": "Luego otra vez silencio.",
    "Rispondi o rifiuta pensando. Poi quel canale si chiude. Iris non è fatta per parlare al posto tuo: è fatta perché le cose basilari del quotidiano non ti rubino più le mani.": "Responde o rechaza pensando. Luego ese canal se cierra. Iris no está hecha para hablar por ti: está hecha para que las cosas básicas del día a día ya no te roben las manos.",
    "Il quotidiano,": "Lo cotidiano,",
    "invisibile.": "invisible.",
    "Qui crei l’account e calibri la cuffia. Fuori da questa pagina il futuro che immaginavi deve sparire dalla vista: pensi, e casa, musica e telefono rispondono.": "Aquí creas la cuenta y calibras el casco. Fuera de esta página, el futuro que imaginabas debe desaparecer de la vista: piensas, y casa, música y teléfono responden.",
    "La cuffia": "El casco",
    "Pensi.": "Piensas.",
    "Succede.": "Sucede.",
    "Una cuffia non invasiva legge l’intento. Niente menu da toccare. Niente “è questo il comando giusto?”.": "Un casco no invasivo lee la intención. Sin menús que tocar. Sin “¿es este el comando correcto?”.",
    "Il telefono": "El teléfono",
    "Anche": "Incluso",
    "in tasca.": "en el bolsillo.",
    "Squilla? Pensi di chiudere: si chiude. Ascolti musica? Pensi di spegnere: si spegne. Il telefono resta dove sta — Iris agisce in background.": "¿Suena? Piensas colgar: se cuelga. ¿Escuchas música? Piensas apagar: se apaga. El teléfono se queda donde está — Iris actúa en segundo plano.",
    "Casa": "Casa",
    "Luci.": "Luces.",
    "Spine.": "Enchufes.",
    "Ambienti.": "Ambientes.",
    "Pensi alla luce: Alexa (o la casa connessa) la accende. Stesso gesto mentale, altro dispositivo.": "Piensas en la luz: Alexa (o la casa conectada) la enciende. El mismo gesto mental, otro dispositivo.",
    "Musica": "Música",
    "Play.": "Play.",
    "Pausa. Next.": "Pausa. Next.",
    "Mentre ascolti, i pensieri vanno alla traccia — non allo schermo. Come chiedere a Siri di cambiare canzone.": "Mientras escuchas, los pensamientos van a la pista — no a la pantalla. Como pedirle a Siri que cambie de canción.",
    "Chiamate": "Llamadas",
    "Rispondi.": "Responde.",
    "O chiudi.": "O cuelga.",
    "Arriva una chiamata: pensi l’azione, il telefono obbedisce. Nessuna conferma da toccare.": "Llega una llamada: piensas la acción, el teléfono obedece. Sin confirmar tocando.",
    "In sintesi": "En resumen",
    "Intento.": "Intención.",
    "Azione.": "Acción.",
    "Silenzio.": "Silencio.",
    "Il sito serve a creare l’account e calibrare la cuffia. Il quotidiano è invisibile: pensi, e basta.": "El sitio sirve para crear la cuenta y calibrar el casco. Lo cotidiano es invisible: piensas, y basta.",
    "Foto temporanee (Unsplash) — le sostituiremo con scatti del prodotto reale.": "Fotos temporales (Unsplash) — las sustituiremos por tomas del producto real.",
    "Accedi alla tua area Iris.": "Accede a tu espacio Iris.",
    "Username": "Usuario",
    "Password": "Contraseña",
    "Email": "Correo",
    "Entra": "Entrar",
    "Password dimenticata?": "¿Has olvidado la contraseña?",
    "Non hai un account?": "¿No tienes cuenta?",
    "Iscriviti": "Regístrate",
    "Hai già un account?": "¿Ya tienes cuenta?",
    "Scegli un username e una mail che non stai già usando su Iris. Nome e cognome li metti al passo dopo.": "Elige un usuario y un correo que no estés usando ya en Iris. Nombre y apellidos van en el paso siguiente.",
    "es. maria_rossi": "p. ej. maria_rossi",
    "la tua mail, es. nome@gmail.com": "tu correo, p. ej. nombre@gmail.com",
    "se ce l’hai, altrimenti lascia vuoto": "si lo tienes, si no déjalo vacío",
    "Password (minimo livello medio)": "Contraseña (nivel medio como mínimo)",
    "Serve almeno: 8 caratteri, una maiuscola, un numero.": "Hace falta al menos: 8 caracteres, una mayúscula, un número.",
    "ID cuffia (opzionale)": "ID del casco (opcional)",
    "Crea account": "Crear cuenta",
    "Recupera password": "Recuperar contraseña",
    "Torna al login": "Volver al inicio de sesión",
    "Invia codice": "Enviar código",
    "Invia codice su": "Enviar código por",
    "SMS (telefono)": "SMS (teléfono)",
    "Username, email o telefono": "Usuario, correo o teléfono",
    "Scrivi il tuo username, la mail o il numero con prefisso (tipo +39…). Iris genera da solo un codice e te lo manda lì (Gmail, Outlook, libero, ecc.: qualunque mail dell’account).": "Escribe tu usuario, el correo o el número con prefijo (tipo +39…). Iris genera por sí sola un código y te lo envía ahí (Gmail, Outlook, Libero, etc.: cualquier correo de la cuenta).",
    "Ti abbiamo mandato una mail. Scrivi il codice di 6 caratteri (lettere e numeri, senza spazi) e scegli la nuova password.": "Te hemos enviado un correo. Escribe el código de 6 caracteres (letras y números, sin espacios) y elige la nueva contraseña.",
    "Ti abbiamo mandato un SMS. Scrivi il codice di 6 caratteri (lettere e numeri, senza spazi) e scegli la nuova password.": "Te hemos enviado un SMS. Escribe el código de 6 caracteres (letras y números, sin espacios) y elige la nueva contraseña.",
    "Invio codici": "Envío de códigos",
    "Conferma la tua email": "Confirma tu correo",
    "Ti abbiamo mandato una email da Iris Nous a": "Te hemos enviado un correo de Iris Nous a",
    "Apri la posta (anche spam), poi premi il pulsante «Conferma iscrizione».": "Abre el correo (también el spam) y pulsa el botón «Confirma el registro».",
    "Finché non confermi, non puoi usare Iris.": "Hasta que confirmes, no puedes usar Iris.",
    "Reinvia email di conferma": "Reenviar correo de confirmación",
    "Mail Iris Nous": "Correo Iris Nous",
    "Username o email": "Usuario o correo",
    "Invia codice via email": "Enviar código por correo",
    "Scrivi username o email dell’account. Iris Nous ti manda un codice nella tua casella (Gmail, Outlook, Libero…).": "Escribe el usuario o el correo de la cuenta. Iris Nous te envía un código a tu bandeja (Gmail, Outlook, Libero…).",
    "Ti abbiamo mandato una mail da Iris Nous. Scrivi il codice di 6 caratteri (lettere e numeri, senza spazi) e scegli la nuova password.": "Te hemos enviado un correo de Iris Nous. Escribe el código de 6 caracteres (letras y números, sin espacios) y elige la nueva contraseña.",
    "Scrivi nome e cognome (senza numeri). La foto è a piacere. Username, email e telefono devono essere tuoi e non già usati da altri.": "Escribe nombre y apellidos (sin números). La foto es opcional. Usuario, correo y teléfono deben ser tuyos y no estar ya usados por otras personas.",
    "Abbiamo inviato un codice via SMS. Inseriscilo e scegli la nuova password.": "Hemos enviado un código por SMS. Introdúcelo y elige la nueva contraseña.",
    "Codice ricevuto": "Código recibido",
    "Nuova password": "Nueva contraseña",
    "Ripeti nuova password": "Repite la nueva contraseña",
    "Imposta nuova password": "Establecer nueva contraseña",
    "Password attuale": "Contraseña actual",
    "Aggiorna password": "Actualizar contraseña",
    "Tocca qui se non vai avanti": "Toca aquí si no avanzas",
    "Accesso...": "Accediendo...",
    "Profilo": "Perfil",
    "Passo 2 di 3": "Paso 2 de 3",
    "I tuoi dati": "Tus datos",
    "Nome e cognome senza numeri. La foto è facoltativa. L’username resta univoco; email e telefono pure.": "Nombre y apellidos sin números. La foto es opcional. El usuario sigue siendo único; el correo y el teléfono también.",
    "Account non verificato": "Cuenta no verificada",
    "Puoi usare Iris lo stesso. Verifica email o telefono quando vuoi: il codice arriva via messaggio.": "Puedes usar Iris igual. Verifica el correo o el teléfono cuando quieras: el código llega por mensaje.",
    "Foto profilo": "Foto de perfil",
    "(opzionale)": "(opcional)",
    "Scegli una foto (JPG / PNG / WebP, max 2.5 MB)": "Elige una foto (JPG / PNG / WebP, máx. 2.5 MB)",
    "Salva foto": "Guardar foto",
    "Anagrafica": "Datos personales",
    "Nome": "Nombre",
    "Cognome": "Apellidos",
    "Email verificata": "Correo verificado",
    "Email non verificata": "Correo no verificado",
    "Prefisso e telefono": "Prefijo y teléfono",
    "Prefisso": "Prefijo",
    "Numero senza prefisso": "Número sin prefijo",
    "Cerca paese…": "Busca país…",
    "Scegli la bandiera/prefisso: si fissa, poi digita solo le cifre del numero.": "Elige la bandera/prefijo: se fija, luego escribe solo las cifras del número.",
    "Telefono verificato": "Teléfono verificado",
    "Telefono non verificato": "Teléfono no verificado",
    "Etichetta dispositivo (opzionale)": "Etiqueta del dispositivo (opcional)",
    "Come ti identifichi": "Cómo te identificas",
    "Scegli l’opzione con cui preferisci essere indirizzata/o/ə nel sito.": "Elige cómo prefieres que te traten en el sitio.",
    "Donna": "Mujer",
    "Uomo": "Hombre",
    "Non binario": "No binario",
    "Salva": "Guardar",
    "Continua": "Continuar",
    "Verifica account": "Verificar cuenta",
    "Non obbligatoria. Se non la fai, resta segnalata nell’area personale.": "No es obligatoria. Si no la haces, queda marcada en tu área personal.",
    "Invia codice email": "Enviar código de correo",
    "Codice email": "Código de correo",
    "Conferma email": "Confirmar correo",
    "Invia codice SMS": "Enviar código SMS",
    "Codice SMS": "Código SMS",
    "Conferma telefono": "Confirmar teléfono",
    "Account verificato.": "Cuenta verificada.",
    "Account verificato": "Cuenta verificada",
    "Elimina account": "Eliminar cuenta",
    "Eliminare definitivamente l’account?": "¿Eliminar la cuenta de forma permanente?",
    "Area privata": "Área privada",
    "Stato cuffia, attività e utilizzo. Il quotidiano resta invisibile — qui vedi solo il quadro.": "Estado del casco, actividad y uso. Lo cotidiano sigue invisible — aquí solo ves el panorama.",
    "Il tuo ecosistema Iris Nous. Accedi da qualsiasi dispositivo, collega i servizi e lascia che il cloud orchestri cuffia, casa, musica e telefono.": "Tu ecosistema Iris Nous. Entra desde cualquier dispositivo, conecta los servicios y deja que la nube orqueste casco, casa, música y teléfono.",
    "Account cloud": "Cuenta en la nube",
    "Integrazioni & Ecosistema": "Integraciones & ecosistema",
    "Un hub, ogni dispositivo": "Un hub, cada dispositivo",
    "Configura ogni servizio da qui — PC, smartphone o tablet. Il backend resta l’orchestratore universale.": "Configura cada servicio desde aquí — PC, smartphone o tablet. El backend sigue siendo el orquestador universal.",
    "Hardware": "Hardware",
    "Pronta": "Listo",
    "Da nominare": "Por nombrar",
    "Identifica la cuffia BCI collegata al tuo account. Quando arriverà l’hardware reale, nome e ID resteranno il riferimento del dispositivo.": "Identifica el casco BCI vinculado a tu cuenta. Cuando llegue el hardware real, el nombre y el ID seguirán siendo la referencia del dispositivo.",
    "Media": "Media",
    "Connesso": "Conectado",
    "Non connesso": "No conectado",
    "Collegato": "Conectado",
    "Una volta connesso, la cuffia controlla la musica su qualsiasi dispositivo attivo: telefono, PC o speaker.": "Una vez conectado, el casco controla la música en cualquier dispositivo activo: teléfono, PC o altavoz.",
    "Collega Spotify per far sì che la cuffia controlli la musica su qualsiasi dispositivo attivo — telefono, PC o speaker — senza scegliere dove stai ascoltando.": "Conecta Spotify para que el casco controle la música en cualquier dispositivo activo — teléfono, PC o altavoz — sin elegir dónde estás escuchando.",
    "Scollega Spotify": "Desconectar Spotify",
    "Collega Spotify": "Conectar Spotify",
    "Domotica": "Domótica",
    "Smart Home": "Smart Home",
    "In ascolto": "Escuchando",
    "Iris orchestra accensione e spegnimento dei dispositivi IoT tramite Home Assistant. Il pensiero diventa un comando verso luci, prese e scene — su qualsiasi schermo da cui apri l’hub.": "Iris orquesta el encendido y el apagado de los dispositivos IoT a través de Home Assistant. El pensamiento se vuelve un comando hacia luces, enchufes y escenas — en cualquier pantalla desde la que abras el hub.",
    "Accendi": "Encender",
    "Spegni": "Apagar",
    "Chiamate / App": "Llamadas / Apps",
    "Smartphone": "Smartphone",
    "Ponte attivo": "Puente activo",
    "Opzionale": "Opcional",
    "Ponte opzionale": "Puente opcional",
    "Per intercettare chiamate native o notifiche, il telefono deve agire da Ponte. Non è un passaggio obbligatorio: è una funzione avanzata dell’ecosistema.": "Para interceptar llamadas nativas o notificaciones, el teléfono debe actuar de puente. No es un paso obligatorio: es una función avanzada del ecosistema.",
    "In linea ora": "En línea ahora",
    "Bridge in attesa": "Bridge en espera",
    "Associa con QR": "Vincular con QR",
    "Apri il ponte": "Abrir el puente",
    "Altre aree": "Otras áreas",
    "Ponte smartphone": "Puente del smartphone",
    "Funzione avanzata": "Función avanzada",
    "Estendi Iris Nous al tuo Smartphone: intercetta chiamate e notifiche in tempo reale tenendo aperto il bridge sul tuo dispositivo mobile.": "Extiende Iris Nous a tu smartphone: intercepta llamadas y notificaciones en tiempo real manteniendo abierto el bridge en tu dispositivo móvil.",
    "QR e codice di associazione": "QR y código de vinculación",
    "Apri questa pagina sul telefono con lo stesso account, inquadra il QR oppure inserisci il codice. Il telefono diventa un ponte dell’ecosistema, non un obbligo di setup.": "Abre esta página en el teléfono con la misma cuenta, escanea el QR o introduce el código. El teléfono se convierte en un puente del ecosistema, no en un paso obligatorio de configuración.",
    "Inquadra il QR col telefono (dopo il login).": "Escanea el QR con el teléfono (después de iniciar sesión).",
    "Telefono associato": "Teléfono vinculado",
    "Scollega e genera nuovo codice": "Desvincular y generar un código nuevo",
    "Conferma codice (dal telefono)": "Confirmar código (desde el teléfono)",
    "Attiva il ponte": "Activar el puente",
    "Quando vuoi chiamate e notifiche in diretta, tieni aperta la pagina": "Cuando quieras llamadas y notificaciones en directo, mantén abierta la página",
    "sul dispositivo mobile: è il bridge dell’ecosistema.": "en el dispositivo móvil: es el bridge del ecosistema.",
    "Non in linea": "Sin conexión",
    "Spotify (musica vera)": "Spotify (música de verdad)",
    "Apri Spotify sul dispositivo che sta riproducendo, metti in play una playlist, poi prova il test. Serve Spotify Premium. La cuffia controllerà la musica su qualsiasi player attivo.": "Abre Spotify en el dispositivo que está reproduciendo, pon en play una lista y luego lanza la prueba. Hace falta Spotify Premium. El casco controlará la música en cualquier reproductor activo.",
    "Collega l’account Spotify: la cuffia controllerà la musica su telefono, PC o speaker, ovunque sia attivo il player.": "Conecta la cuenta de Spotify: el casco controlará la música en el teléfono, el PC o el altavoz, allá donde esté activo el reproductor.",
    "Spotify non è ancora configurato sul server (chiavi API). Possiamo associarlo al prossimo passo: senza chiavi il test canzone resta in simulazione.": "Spotify aún no está configurado en el servidor (claves API). Podemos vincularlo en el siguiente paso: sin claves, la prueba de canción se queda en simulación.",
    "Test rapido": "Prueba rápida",
    "Dal hub: simula “prossima canzone” verso il ponte.": "Desde el hub: simula “siguiente canción” hacia el puente.",
    "Prossima canzone": "Siguiente canción",
    "Apri telefono live": "Abrir teléfono en vivo",
    "Torna all’ecosistema": "Volver al ecosistema",
    "Cuffia": "Casco",
    "Cuffia non nominata": "Casco sin nombre",
    "Associata": "Vinculado",
    "Non associata": "No vinculado",
    "in linea": "en línea",
    "Verifica ora": "Verificar ahora",
    "Dati": "Datos",
    "Anagrafica e foto": "Datos y foto",
    "Colori / segnale": "Colores / señal",
    "Associazione": "Vinculación",
    "Telefono · Spotify": "Teléfono · Spotify",
    "Telefono live": "Teléfono en vivo",
    "In linea": "En línea",
    "Apri sul cellulare": "Abrir en el móvil",
    "Sicurezza account": "Seguridad de la cuenta",
    "Funzionamento": "Funcionamiento",
    "Calibrazione completa": "Calibración completa",
    "da fare": "por hacer",
    "Attività cerebrale (demo)": "Actividad cerebral (demo)",
    "Utilizzo": "Uso",
    "Intenti": "Intenciones",
    "Sessioni": "Sesiones",
    "Minuti": "Minutos",
    "Ultima attività": "Última actividad",
    "Impostazioni rapide": "Ajustes rápidos",
    "Nome cuffia": "Nombre del casco",
    "Note": "Notas",
    "Verifica": "Verificar",
    "Ti inviamo un codice a 6 caratteri via email. Aprilo nella posta e inseriscilo qui sotto.": "Te enviamos un código de 6 caracteres por correo. Ábrelo en la bandeja e introdúcelo aquí debajo.",
    "Codice ricevuto via email": "Código recibido por correo",
    "Stai sul sito locale del PC. Gli account del telefono (Spotify incluso) sono sul sito online.": "Estás en el sitio local del PC. Las cuentas del teléfono (Spotify incluido) están en el sitio en línea.",
    "Apri il sito online": "Abrir el sitio en línea",
    "Password non corretta. Puoi recuperarla da «Password dimenticata?».": "Contraseña incorrecta. Puedes recuperarla desde «¿Has olvidado la contraseña?».",
    "Notifiche": "Notificaciones",
    "Chatta con noi": "Chatea con nosotros",
    "Contattaci": "Contáctanos",
    "Supporto": "Soporte",
    "Scrivi al team": "Escribe al equipo",
    "Scrivi al team Iris Nous. Puoi usare la chat oppure una richiesta via email: ti rispondiamo di persona sulla tua casella.": "Escribe al equipo de Iris Nous. Puedes usar el chat o una solicitud por correo: te respondemos en persona a tu bandeja.",
    "Richiesta via email": "Solicitud por correo",
    "Oggetto": "Asunto",
    "Di cosa hai bisogno?": "¿Qué necesitas?",
    "Messaggio": "Mensaje",
    "Invia": "Enviar",
    "Home": "Inicio",
    "Agente AI": "Agente de IA",
    "Parla con l'Agente AI per supporto o per richiedere un contatto telefonico": "Habla con el Agente de IA para soporte o para pedir un contacto telefónico",
    "Scrivi un messaggio…": "Escribe un mensaje…",
    "Compila il modulo: ti rispondiamo di persona sulla tua casella email.": "Rellena el formulario: te respondemos en persona a tu correo.",
    "Serve un dominio con estensione, es. nome@gmail.com": "Hace falta un dominio con extensión, p. ej. nombre@gmail.com",
    "Prefisso internazionale": "Prefijo internacional",
    "Chi sei": "Quién eres",
    "Nome ed email servono per saperti rispondere.": "Nombre y correo hacen falta para poder responderte.",
    "Stai scrivendo come": "Estás escribiendo como",
    "Scrivi il tuo nome, così sappiamo chi ci ha scritto.": "Escribe tu nombre para saber quién nos ha escrito.",
    "Scrivi al team Iris Nous. Ti rispondiamo di persona.": "Escribe al equipo de Iris Nous. Te respondemos en persona.",
    "Scrivi il problema nel form. Ti rispondiamo di persona qui e via email, da telefono o da computer.": "Escribe el problema en el formulario. Te respondemos aquí y por correo, desde el teléfono o el ordenador.",
    "Descrivi il problema": "Describe el problema",
    "Scrivi cosa non funziona…": "Escribe qué no funciona…",
    "Team Iris Nous": "Equipo Iris Nous",
    "Vedi le risposte": "Ver las respuestas",
    "Hai già scritto da un altro telefono o dal computer? Inserisci la stessa email per vedere le risposte.": "¿Ya escribiste desde otro teléfono o el ordenador? Introduce el mismo correo para ver las respuestas.",
    "Se la mail non arriva, usa questo codice:": "Si el correo no llega, usa este código:",
    "Telefono": "Teléfono",
    "Il pensiero diventa azione. Niente comandi vocali, nessun movimento. Iris Nous è l'interfaccia neurale che decodifica le tue intenzioni e le connette direttamente al mondo fisico. Immagina, e accade.": "El pensamiento se convierte en acción. Sin comandos de voz, sin movimiento. Iris Nous es la interfaz neural que descifra tus intenciones y las conecta con el mundo físico. Imagina, y sucede.",
    "Il pensiero, in chiaro.": "El pensamiento, en claro.",
    "Catturiamo l'invisibile. I tuoi impulsi cerebrali vengono processati in tempo reale da un'intelligenza artificiale adattiva. Il rumore scompare, resta solo la purezza della tua intenzione, codificata in istanti.": "Capturamos lo invisible. Tus impulsos cerebrales se procesan en tiempo real con una inteligencia artificial adaptativa. El ruido desaparece; queda la pureza de tu intención, codificada en instantes.",
    "In tasca.": "En el bolsillo.",
    "Non in mano.": "No en la mano.",
    "Cambia ritmo senza muovere un dito. L'architettura software traduce il tuo stato di focus in comandi fluidi per il tuo ecosistema multimediale. La tecnologia c'è, ma non si vede. La vivi.": "Cambia el ritmo sin mover un dedo. El software traduce tu estado de foco en comandos fluidos para tu ecosistema multimedia. La tecnología está, pero no se ve. La vives.",
    "La casa ti ascolta.": "La casa te escucha.",
    "Il confine tra mente e materia si dissolve. Concentrati, e l'ambiente reagisce. Le luci si accendono, gli scenari cambiano. Il controllo del tuo spazio vitale è ora una naturale estensione della tua volontà.": "El límite entre mente y materia se disuelve. Concéntrate, y el ambiente reacciona. Se encienden las luces, cambian las escenas. El control de tu espacio vital es ahora una extensión natural de tu voluntad.",
    "Il ritmo, nel pensiero.": "El ritmo, en el pensamiento.",
    "Senza mani.": "Sin las manos.",
    "Iris Nous — Tesi di Laurea in Informatica. Università di Torino (UNITO). Sede: Torino.": "Iris Nous — Trabajo de fin de grado en Informática. Universidad de Turín (UNITO). Turín.",
    "Acquisizione EEG | Machine Learning | Integrazioni IoT": "Adquisición EEG | Machine Learning | Integraciones IoT",
    "Design & Code:": "Diseño y código:",
    "GitHub": "GitHub",
    "Docs": "Docs",
    "© 2026 Iris Nous. Il futuro dell'interazione.": "© 2026 Iris Nous. El futuro de la interacción.",
}
